import Header from './header'
import "../src/app/globals.css"
import Footer from './footer'
import Script from 'next/script'



// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  

 

 return (
   <html lang="en" >
     <head>
     <link rel="icon" href="/favicon.png" />
       <Script type="text/javascript" defer charSet="utf-8" id="tealium-tag-7110" src="https://www.google-analytics.com/analytics.js"></Script>
       <Script type="text/javascript"  strategy="beforeInteractive" id="tealium-tag-7110"  defer
         dangerouslySetInnerHTML={{
           __html: `
           async function getGeo() {
            var geo = window.sessionStorage.getItem('tealium_geo') || (function () {
              // https://www.iso.org/obp/ui/#search
              // http://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes
              var eu = { at: 1, be: 1, bg: 1, hr: 1, cy: 1, cz: 1, dk: 1, ee: 1, fi: 1, fr: 1, de: 1, el: 1, hu: 1, ie: 1, it: 1, lv: 1, lt: 1, lu: 1, mt: 1, nl: 1, pl: 1, pt: 1, ro: 1, sk: 1, si: 1, es: 1, se: 1, uk: 1 },
                loc = 'country_code=na,region_code=na,city=na,areacode=na,county=na,zip=na',
                client = new XMLHttpRequest();
              function addData(loc) {
                var geo = loc.split(',').reduce(function (o, v) {
                  v = v.toLowerCase().split('=');
                  if (/city|region|country/.test(v[0])) {
                    o['location_' + v[0]] = v[1];
                  }
                  if (/country_code/.test(v[0])) {
                    if (v[1] !== 'na') {
                      o.location_is_gdpr = eu[v[1]] ? 1 : 0;
                    }
                  }
                  return o;
                }, {});
                geo = window.JSON.stringify(geo);
                window.sessionStorage.setItem('tealium_geo', geo);
                return geo;
              }
              try {
                // 3rd arg false makes the request synchronous
                client.open('GET', 'https://akamai.tiqcdn.com/location/location.js', false); client.send(null);
                if (client.status === 200) {
                  loc = client.getResponseHeader('X-EdgeScape-Location');
                }
               
              }
              catch (err) {
                console.error('Error Opening Tealium Geolocation: ' + err);
              }
              return addData(loc);
            }());
            var geo_data = window.JSON.parse(geo);
            window.utag_data = Object.assign(window.utag_data, geo_data);
            if (!checkCookie('OPTOUTMULTI_GEO')) {
              setCookie('OPTOUTMULTI_GEO', geo_data.location_country_code.toUpperCase(), null);
            }
          }
       `,}}
       />
     </head>
    
 
  
     
     <body>
       <Header />
       {children}
       <Footer/>
       
     </body>
    </html>
  )
}